### ISSUE TITLE
export not working 

### ISSUE THREAD

**Issue by abhizeetyadav** [tiledocs/tiledocs-editor#2]
after exporting in "Export in HTML and Download as Zip File". the zip file is downloaded but after opening the index.html file, the content of site is not showing.

![Screenshot 2024-12-08 155757](https://github.com/user-attachments/assets/8104c5fc-ec3e-4a84-a35b-6e96635cb194)

**Comment by ipselon** [comment]
The generated package with static HTML is designed to be run on an HTTP server. 

Therefore, if you want to run it on your local computer, you will need to launch it through an ExpressJS server. 

Do you know how to install and configure it?

**Comment by abhizeetyadav** [comment]
no, can you please help me on that?

**Comment by ipselon** [comment]
Here is the ChatGPT answer... just follow the instructions. 
https://chatgpt.com/share/6755a9ae-c858-8010-b97a-1ef3ad3b5d0c

P.S.
Export with the base URL: `http://localhost:3000`

**Comment by abhizeetyadav** [comment]
thanks its working now
