### ISSUE TITLE
409 error on GitHub project sync

### ISSUE THREAD

**Issue by nicholasareed** [tiledocs/tiledocs-editor#3]
I followed the instructions for setting up the GitHub sync, but trying to save results in a 409 response from the github API, with the message (from the github api): "Git Repository is empty." 

<img width="461" alt="Screenshot 2024-12-18 at 11 40 23 PM" src="https://github.com/user-attachments/assets/2b34e5e3-5f96-4f8f-a199-3c7f2b52c45c" />

It is supposed to be an empty repository, correct?

**Comment by ipselon** [comment]
@nicholasareed yes, the repository where you want to save the data should be empty. And it should have a branch that is the default one.

**Comment by nicholasareed** [comment]
An empty repository doesnt have a default branch, so I am confused what is
needed. I create a github repo using the web ui, what else is necessary?
Committing a blank file or something?

**Comment by ipselon** [comment]
Sorry, my mistake. Usually, when creating a new repository using the GitHub UI, you either create a license file or a Readme file. Therefore, GitHub automatically creates a new branch. 

Create a new repository with the option to create a Readme file, and then you will have a default branch.

**Comment by nicholasareed** [comment]
👍 thanks! There is definitely a difference between an "empty" repository and one with a file in it, so probably worth updating the docs to reflect that (or allow a real "empty" repository to be used, that is preferable and simpler!). Works for me when I add a file though, much appreciated and we'll try to leave feedback as we use it!

**Comment by ipselon** [comment]
Well, regarding what counts as an empty repository, technically, you’re right. But I can’t really imagine a scenario where a repository would be useful without a default branch. 

I’ll probably implement a check for the existence of a branch and have it created automatically if it’s missing. 

Thank you for helping me identify this bug.
